/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p10514904;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Valent
 */
public class FPengembalian extends javax.swing.JFrame {
    Connection conn;
    private DefaultTableModel tabModel;
    /**
     * Creates new form FPengembalian
     */
    public FPengembalian() {
        initComponents();
        AutoNumber();
        setJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNoPinjam = new javax.swing.JTextField();
        txtNoAnggota = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtDenda = new javax.swing.JTextField();
        txtTglPinjam = new javax.swing.JTextField();
        txtTglKembali = new javax.swing.JTextField();
        txtTglDikembalikan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTerlambat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNoPengembalian = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDetailPinjam = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        BTambah = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BBatal = new javax.swing.JButton();
        BClose = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel1.setText("No Pinjam");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel2.setText("No Anggota");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel4.setText("Denda (Rp.)");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel5.setText("Tgl Pinjam");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel6.setText("Tgl Kembali");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel7.setText("Tgl Dikembalikan");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel8.setText("Terlambat");

        txtNoPinjam.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        txtNoPinjam.setEnabled(false);
        txtNoPinjam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoPinjamKeyPressed(evt);
            }
        });

        txtNoAnggota.setEditable(false);
        txtNoAnggota.setBackground(new java.awt.Color(153, 153, 153));
        txtNoAnggota.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtNoAnggota.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        txtNama.setEditable(false);
        txtNama.setBackground(new java.awt.Color(153, 153, 153));
        txtNama.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtNama.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        txtDenda.setEditable(false);
        txtDenda.setBackground(new java.awt.Color(153, 153, 153));
        txtDenda.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txtDenda.setForeground(new java.awt.Color(255, 0, 0));
        txtDenda.setDisabledTextColor(new java.awt.Color(255, 0, 0));

        txtTglPinjam.setEditable(false);
        txtTglPinjam.setBackground(new java.awt.Color(153, 153, 153));
        txtTglPinjam.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtTglPinjam.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        txtTglKembali.setEditable(false);
        txtTglKembali.setBackground(new java.awt.Color(153, 153, 153));
        txtTglKembali.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtTglKembali.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        txtTglDikembalikan.setEditable(false);
        txtTglDikembalikan.setBackground(new java.awt.Color(153, 153, 153));
        txtTglDikembalikan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtTglDikembalikan.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel9.setText("Hari");

        txtTerlambat.setEditable(false);
        txtTerlambat.setBackground(new java.awt.Color(153, 153, 153));
        txtTerlambat.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txtTerlambat.setForeground(new java.awt.Color(255, 0, 0));
        txtTerlambat.setDisabledTextColor(new java.awt.Color(255, 0, 0));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel10.setText("No Kembali");

        txtNoPengembalian.setBackground(new java.awt.Color(255, 255, 0));
        txtNoPengembalian.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        txtNoPengembalian.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNoPengembalian.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("@COPYRIGHT VALENT_10514904");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 37, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTerlambat, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addComponent(txtTglDikembalikan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(txtTglKembali, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTglPinjam, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNoPengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(txtNoPinjam)
                            .addComponent(txtNoAnggota)
                            .addComponent(txtDenda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtNoPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNoPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTglDikembalikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(txtTerlambat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tDetailPinjam.setBackground(new java.awt.Color(51, 255, 255));
        tDetailPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Kode Buku", "Judul Buku"
            }
        ));
        jScrollPane1.setViewportView(tDetailPinjam);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BTambah.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        BTambah.setText("Create");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });

        BSimpan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        BSimpan.setText("Confirm");
        BSimpan.setEnabled(false);
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });

        BBatal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        BBatal.setText("Cancel");
        BBatal.setEnabled(false);
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTambah)
                .addGap(27, 27, 27)
                .addComponent(BSimpan)
                .addGap(35, 35, 35)
                .addComponent(BBatal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTambah)
                    .addComponent(BSimpan)
                    .addComponent(BBatal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BClose.setBackground(new java.awt.Color(204, 204, 204));
        BClose.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BCloseMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("Close");

        javax.swing.GroupLayout BCloseLayout = new javax.swing.GroupLayout(BClose);
        BClose.setLayout(BCloseLayout);
        BCloseLayout.setHorizontalGroup(
            BCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BCloseLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        BCloseLayout.setVerticalGroup(
            BCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BCloseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(26, 26, 26))
        );

        jLabel12.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jLabel12.setText("PENGEMBALIAN BUKU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel12)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel12)
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BClose, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        setSize(new java.awt.Dimension(952, 706));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     
    public void AutoNumber() {
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:PERPUS");
            String sql="Select * from Pengembalian ORDER BY NoPengembalian DESC";
            Statement stt = conn.createStatement();
            ResultSet rs = stt.executeQuery(sql);
            if (rs.next()) {
                String NoPengembalian = rs.getString("NoPengembalian").substring(1);
                String AN = "" + (Integer.parseInt(NoPengembalian) + 1);
                String Nol = "";

                if(AN.length()==1)
                {Nol = "000";}
                else if(AN.length()==2)
                {Nol = "00";}
                else if(AN.length()==3)
                {Nol = "0";}
                else if(AN.length()==4)
                {Nol = "";}
                txtNoPengembalian.setText("K" + Nol + AN);//sesuaikan dengan variable namenya
            } else {
                txtNoPengembalian.setText("K0001");//sesuaikan dengan variable namenya
            }
            rs.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();//penanganan masalah
        }
    }
      
    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        resetForm();
    }//GEN-LAST:event_BBatalActionPerformed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:PERPUS");
            if(txtNoPinjam.getText().isEmpty() || tabModel.getRowCount()==0 ){
                JOptionPane.showMessageDialog(this,"Silahkan Input No Pinjam");
            } else {
                // Menyimpan ke Tabel Pinjam
                String sql="insert into Pengembalian values(?,?,?,?,?,?,?)";
                PreparedStatement st=conn.prepareStatement(sql);
                st.setString(1,txtNoPengembalian.getText());
                st.setString(2,txtNoPinjam.getText());
                st.setString(3,txtDenda.getText());
                st.setString(4,txtTglPinjam.getText());
                st.setString(5,txtTglKembali.getText());
                st.setString(6,txtTglDikembalikan.getText());
                st.setString(7,txtTerlambat.getText());
                int rs= st.executeUpdate();

                String KodeBuku; int rs2=0;

                int jum=tabModel.getRowCount();
                for(int i=0;i<jum;i++){
                    // Menyimpan Ke detail Pinjam
                    String sql2="insert into DetailPengembalian values(?,?,?)";
                    PreparedStatement st2=conn.prepareStatement(sql2);
                    KodeBuku = tabModel.getValueAt(i, 1).toString();
                    st2.setString(1,txtNoPengembalian.getText());
                    st2.setString(2,KodeBuku);
                    st2.setString(3,"1");
                    rs2= st2.executeUpdate();
                    // Merubah status Buku
                    String sql3="update Buku set Status=? where KodeBuku=?";
                    PreparedStatement st3=conn.prepareStatement(sql3);
                    st3.setString(1,"Ada");
                    st3.setString(2, KodeBuku);
                    st3.executeUpdate();
                }
                if((rs>0) && (rs2>0)){
                    JOptionPane.showMessageDialog(this,"Input Berhasil");
                    AutoNumber();
                    resetForm();
                    hapusIsiJTable();
                } else
                JOptionPane.showMessageDialog(this,"Input Gagal");
                conn.close();
            }

        } // akhir try
        catch(Exception e){
            System.out.println("Exception " +e );
        }
    }//GEN-LAST:event_BSimpanActionPerformed

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        txtNoPengembalian.setEnabled(false);
        txtNoPinjam.setEnabled(true);

        BSimpan.setEnabled(true);
        BBatal.setEnabled(true);
    }//GEN-LAST:event_BTambahActionPerformed

    private void txtNoPinjamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoPinjamKeyPressed
        if(evt.getKeyCode()==10){
            getPinjam();
            String Id_Pinjam = txtNoPinjam.getText();
            tampilDataKeJTable(Id_Pinjam);
        }
    }//GEN-LAST:event_txtNoPinjamKeyPressed

    private void BCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BCloseMouseClicked
        dispose();
    }//GEN-LAST:event_BCloseMouseClicked
    
    public void resetForm(){
        txtNoPinjam.setText(null);
        txtNama.setText("");
        txtNoAnggota.setText("");
        txtTglPinjam.setText("");
        txtTglKembali.setText("");
        txtTglDikembalikan.setText("");
        txtTerlambat.setText("");
        txtDenda.setText("");
    }
    
    private void getPinjam(){
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn = DriverManager.getConnection("jdbc:odbc:PERPUS");
            String sql = "SELECT *,Nama FROM Pinjam INNER JOIN Anggota on Pinjam.NoAnggota = Anggota.NoAnggota Where NoPinjam=?";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, txtNoPinjam.getText());
            ResultSet rs = st.executeQuery();
            if (rs.next()) {
                Date tglPinjam = rs.getDate("tglPinjam");
                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                String formatTglPinjam = formatter.format(tglPinjam);
                
                Date tglKembali = rs.getDate("tglKembali");
                SimpleDateFormat simpleFormat = new SimpleDateFormat("dd/MM/yyyy");
                String formatTglKembali = simpleFormat.format(tglKembali);
                
                String Nama = rs.getString("Nama");
                txtNama.setText(Nama);
                txtNoAnggota.setText(rs.getString("NoAnggota"));
                txtTglPinjam.setText(formatTglPinjam);
                txtTglKembali.setText(formatTglKembali);
                
                
                Date tgl_sekarang = new Date();
                SimpleDateFormat format=new SimpleDateFormat("dd/MM/yyyy");
                String formatTglDikembalikan=format.format(tgl_sekarang);
                txtTglDikembalikan.setText(formatTglDikembalikan);
                
                SimpleDateFormat myFormat = new SimpleDateFormat("dd/MM/yyyy");
                String tgl = formatTglKembali;
                String tgl2 = formatTglDikembalikan;
                
                int denda = 0;
                try {
                    Date date1 = myFormat.parse(tgl);
                    Date date2 = myFormat.parse(tgl2);
                    long diff = date2.getTime() - date1.getTime();
                    denda = (int) (TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS));
                    if(denda >= 0){
                        txtTerlambat.setText(String.valueOf(denda));
                    }else{
                        denda = 0;
                        txtTerlambat.setText("0");
                    }
                } catch (ParseException e) {
                    e.printStackTrace();
                }
                int hasil = 500 * denda;
                txtDenda.setText(String.valueOf(hasil));
            } else {
                JOptionPane.showMessageDialog(this, "No Pinjam Tidak ada!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                txtNoPinjam.setText("");
            }
        }
        catch (Exception e) {
            System.out.println("Koneksi Gagal " + e.getMessage());
        }
    }
    
    private void setJTable(){
        String [] JudulKolom={"No","Kode Buku","Judul"};
        tabModel = new DefaultTableModel(null, JudulKolom){
                      boolean[] canEdit = new boolean [] { false, false };
                      @Override
                      public boolean isCellEditable(int rowIndex, int columnIndex) {
                       return canEdit [columnIndex];
                      }
                  };
        tDetailPinjam.setModel(tabModel);
        tDetailPinjam.getColumnModel().getColumn(0).setPreferredWidth(80);
        tDetailPinjam.getColumnModel().getColumn(0).setPreferredWidth(100);
        tDetailPinjam.getColumnModel().getColumn(1).setPreferredWidth(200);
    }
    
    public void hapusIsiJTable() {
        int row = tabModel.getRowCount();
        for (int i = 0; i < row; i++) {
          tabModel.removeRow(0);
        }
    }
    
    public void tampilDataKeJTable(String Id_Pinjam) {
        hapusIsiJTable();
        try {
            conn.close();
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            conn=DriverManager.getConnection("jdbc:odbc:PERPUS");   // import java.sql.DriverManager
            String sql="SELECT *,Judul from DetailPinjam INNER JOIN Buku on DetailPinjam.KodeBuku = Buku.KodeBuku  WHERE NoPinjam = '"+Id_Pinjam+"'" ;
            PreparedStatement st=conn.prepareStatement(sql);
            ResultSet rs=st.executeQuery();
            String kdBuku,jdBuku;
            int no=0;
            while(rs.next()){
             no=no+1;
             kdBuku=rs.getString("KodeBuku");
             jdBuku=rs.getString("Judul");
             Object Data[]={no,kdBuku,jdBuku};
             tabModel.addRow(Data);
          }
      }
        catch (Exception e) {
            System.out.println("Gagal " + e.getMessage());
        }
    }
    
    public String formatTanggal(String tgl) throws ParseException{
        String input = tgl;
        SimpleDateFormat parser = new SimpleDateFormat("dd/MM/yyyy");
        Date date = parser.parse(input);
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        String formattedDate = formatter.format(date);
        return tgl;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBatal;
    private javax.swing.JPanel BClose;
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton BTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tDetailPinjam;
    private javax.swing.JTextField txtDenda;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoAnggota;
    private javax.swing.JTextField txtNoPengembalian;
    private javax.swing.JTextField txtNoPinjam;
    private javax.swing.JTextField txtTerlambat;
    private javax.swing.JTextField txtTglDikembalikan;
    private javax.swing.JTextField txtTglKembali;
    private javax.swing.JTextField txtTglPinjam;
    // End of variables declaration//GEN-END:variables
}
